replicaCount: 1

image:
  repository: goharbor.dudenas.work/public/bka-single-html-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: helmapp.dudenas.work
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}